[9546]  DeferredLock, DeferredSemaphore, etc as async context managers
twisted/twisted pull request #1078
Opened 2018-10-18 21:40 UTC by wiml

* [X] There is [an associated ticket in Trac](https://twistedmatrix.com/trac/ticket/9546)
* [X] The changes pass minimal style checks
* [X] I have created a newsfragment in src/twisted/newsfragments/
* [X] I have updated the automated tests.

This is a pretty small change, most of the commit is the unit tests.

For the code which isn't parsable on older versions of Python, I copied the pattern used in other "`.3only`" tests.

2019-01-27 21:28 UTC, twm requested changes
I noted some missing docstrings (style issue), but functionally this looks to be in great shape.

I do think that there should be coverage of the exception case, something like this:

```python
    @ensuringDeferred
    async def test_asyncWithLockException(self):
        """
        C{Lock} does not handle exceptions when used as an async context
        manager.
        """
        lock = defer.DeferredLock()
        with self.assertRaises(IndentationError):
            async with lock:
                self.assertTrue(lock.locked)
                raise IndentationError()
        self.assertFalse(lock.locked)
```

This will be a useful addition to Twisted, so thank you! Since adding tests will involve code, I think there should be a re-review so I am marking this as "changes required". Feel free to ping me for a re-review — I will try to be prompt about it.

2019-01-27 21:28 UTC, twm commented on src/twisted/test/test_defer.py.3only
> +    async def test_asyncWithLock(self):
There should be a docstring here.

2019-01-27 21:28 UTC, twm commented on src/twisted/test/test_defer.py.3only
> +    async def test_asyncWithSemaphore(self):
And a docstring here too.

2019-02-21 08:51 UTC, wiml commented
Sounds good. Commit 55cab3ebb73ef3cff126474b7235f035aee610af should address your feedback.

2019-02-22 04:08 UTC, twm approved these changes
Looks great. Thanks @wiml! I'll go ahead and merge.

2019-02-22 04:11 UTC, merged