Fix for issue #9476 (backoffPolicy OverflowError on attempts higher 1750)
twisted/twisted pull request #1141
Opened 2019-05-17 22:07 UTC by jandelgado

This fixes https://twistedmatrix.com/trac/ticket/9476, where the backoffPolicy raised an OverflowError for connection attempts > 1750 when using the default settings.

## Contributor Checklist:

* [x] There is an associated ticket in Trac. Create a new one at https://twistedmatrix.com/trac/newticket
* [x] The changes pass minimal style checks (see: https://twistedmatrix.com/trac/wiki/TwistedDevelopment#GettingYourPatchAccepted )
* [x] I have created a newsfragment in src/twisted/newsfragments/ (see: https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles )
* [x] I have updated the automated tests.

2019-05-19 05:00 UTC, twm requested changes
First, thanks for this fix! I use `backoffPolicy()` pretty extensively and would have eventually been bitten by this bug.

The changes themselves look good. Thank you for writing tests for this function &mdash; I'm surprised that it slipped in without any. There is just one procedural nit blocking merge: all classes and methods [need docstrings](https://twistedmatrix.com/documents/current/core/development/policy/coding-standard.html). The comments you left are pretty close to what's required.

Thanks again!

2019-05-19 05:00 UTC, twm commented on src/twisted/test/test_application.py
> +    def test_calculates_correct_values(self):
This test needs a docstring per the coding standard: https://twistedmatrix.com/documents/current/core/development/policy/coding-standard.html The same goes to the other two.

2019-05-19 14:36 UTC, jandelgado commented on src/twisted/test/test_application.py
> +    def test_calculates_correct_values(self):
Added docstrings to the tests.

2019-05-19 18:25 UTC, twm approved these changes
Thank you @jandelgado! There is build failure but it is unrelated to your changes so I'm going to correct a nit in the docstring formatting to get it to run again (we just switched to Azure and I don't seem to be able to re-run it in the new system).

(The nit is that the """ should be on their own lines. I guess our linting tools don't catch this. :disappointed: I'd file a bug for this but there is some ongoing work to automate docstring formatting so the ticket would be obsoleted in short order.)

Thanks so much for contributing to Twisted and bearing with our process!

2019-05-19 18:53 UTC, merged

2019-05-20 09:38 UTC, jandelgado commented
Excellent! Thanks for the quick merge.