#11826 Conditionally skip tests that require METHOD_CRYPT
twisted/twisted pull request #11827
Opened 2023-03-17 11:31 UTC by mweinelt

## Scope and purpose

Fixes #11826

The advent of libxcrypt offers new password hashing algorithms to linux distributions, which we are slowly rolling out to our users.

At the same time we are removing support for legacy ciphers, that should not be used any longer in a security-context.

One of these is the traditional crypt method, which the python documentation¹ describes it as the "weakest method" it supports.

This change adds a skip condition to the relevant tests, that checks for the presence of crypt.METHOD_CRYPT in the list of supported hashes.

[1] https://docs.python.org/3/library/crypt.html#crypt.METHOD_CRYPT

## Contributor Checklist:

This process applies to *all* pull requests - no matter how small.
Have a look at [our developer documentation](https://docs.twisted.org/en/latest/core/development/dev-process.html) before submitting your Pull Request.

Below is a non-exhaustive list (as a reminder):

* The title of the PR should describe the changes and starts with the associated issue number, like “#1234 Brief description”.
* A release notes news fragment file was create in src/twisted/newsfragments/ (see: [Release notes fragments docs.](https://docs.twisted.org/en/latest/core/development/dev-process.html#release-notes-management))
* The automated tests were updated.
* Once all checks are green, request a review by leaving a comment that contains exactly the string `please review`.
  Our bot will trigger the review process, by applying the pending review label
  and requesting a review from the Twisted dev team.

2023-03-17 12:09 UTC, mweinelt commented
please review

2023-09-13 23:38 UTC, adiroiban commented
Thanks for the PR.

I don't know what to say, as we don't have a GHA test environment for this.

I guess that we can merge this.

At the same time, I think that crypt will be removed in Python 3.13, so we should look into deprecating this code.

2023-09-13 23:43 UTC, adiroiban approved these changes
I guess that we can merge this.

It looks like we don't have the resources to setup an nixOS testing environment for GitHub Action.

But since we need to remove the usage for `crypt` library for Python 3.13, maybe this can help a bit to identify the places where `crypt` is used.

2023-09-13 23:43 UTC, adiroiban commented on src/twisted/conch/test/test_checkers.py
> +    has_method_crypt = getattr(crypt, "METHOD_CRYPT", None) in crypt.methods
```suggestion
    # We have the crypt main library.
    # But some Python builds might now have the the
    # weakest `crypt.crypt()` method. 
    has_method_crypt = getattr(crypt, "METHOD_CRYPT", None) in crypt.methods
```

2023-09-13 23:56 UTC, exarkun requested changes
Thanks.  Some comments inline.  Also, where's the test for what _does_ happen when the module is missing?

2023-09-13 23:56 UTC, exarkun commented on src/twisted/conch/test/test_checkers.py
> +    has_method_crypt = False
Should be `hasCryptMethod` to follow the Twisted naming convention

2023-09-13 23:56 UTC, exarkun commented on src/twisted/conch/test/test_checkers.py
> +    @skipIf(not has_method_crypt, "Required crypt method is unavailable: METHOD_CRYPT")
This line could be duplicated a lot less.

2024-05-03 21:34 UTC, glyph commented
Looks like the 3.13 builder has covered the lines that were previously skipped!

2026-04-09 23:28 UTC, closed without merging