#11844 Pin pyasn1 dependency for Twisted Conch to version below 0.5
twisted/twisted pull request #11845
Opened 2023-04-23 19:23 UTC by adiroiban

## Scope and purpose

Fixes #11844

The tests are failing with the latest pyans1 version.

Update our deps to depend on older pyasn1.

2023-04-23 19:34 UTC, adiroiban commented
This should be ready for review.

Codecov.io coverage upload failed, and I triggered a retry

needs-review

2023-04-23 20:22 UTC, exarkun commented on src/twisted/conch/newsfragments/11844.bugfix
> +`pyasn1` intorduce a few changes that so far we know that break the Twisted
Typo - `intorduce`

Why "so far as we know"?  Don't we just know it?

2023-04-23 20:41 UTC, adiroiban commented on src/twisted/conch/newsfragments/11844.bugfix
> +test suite.
```suggestion
The `pyasn1` dependency was updated to depend on a version below 0.5.0.
`pyasn1` introduce changes that break the Twisted test suite.
```

Thanks for the review. Hope this is better :)

2023-04-27 18:50 UTC, glyph requested changes
Pinning to an old version of a security-critical dependency is not an option that we should ever consider.

The only acceptable version of this would be to add a `[old_broken_ssh_keys]` extra that would add the pin, that is *not* part of `all` of `all_non_platform`.

2023-04-27 18:55 UTC, adiroiban commented
Thanks Glyph for the review.
I think that this can be closed as won't fix.

The effort should be done on merging https://github.com/twisted/twisted/pull/11843

2023-04-27 18:55 UTC, closed without merging