[#11968] Deprecate twisted.words.
twisted/twisted pull request #11969
Opened 2023-09-08 19:08 UTC by adiroiban

## Scope and purpose

Fixes #11968

This introduces the deprecation warning for twisted.words

2023-09-08 21:30 UTC, glyph requested changes
Let's split the uncontroversial documentation upgrades into a separate branch, and give it at least a week on the mailing list before landing an actual deprecation.

2023-09-08 21:30 UTC, glyph commented on docs/development/compatibility-policy.rst
> +    class WordsDeprecationTests(unittest.TestCase):
this should probably be OldCodeDeprecationTests

2023-09-08 21:31 UTC, adiroiban commented on docs/development/compatibility-policy.rst
> +        def test_deprecationDirect(self):
With typing

```suggestion
        def test_deprecationDirect(self) -> None:
```

2023-09-08 21:58 UTC, adiroiban commented
Thanks for the review and the feedback.

Agree with the move. Docs changes were moved here https://github.com/twisted/twisted/pull/11971

I know that we are still talking about whether or not to deprecate twisted.words

I think this is ready for review... in case we decide to deprecate the code.

needs-review

2023-09-11 17:07 UTC, adiroiban commented
we can keep twisted.words for now. @ralphm will try to keep an eye over this code.

2023-09-11 17:07 UTC, closed without merging