[9470] ESMTPSender: dont't force TLSv1.0 by default
twisted/twisted pull request #1225
Opened 2020-03-03 14:36 UTC by mmilata

Hello, I've also been bitten by matrix-org/synapse#6211 and would like to see if the fix is acceptable for inclusion in Twisted.

## Contributor Checklist:

* [x] The associated ticket in Trac is here: https://twistedmatrix.com/trac/ticket/9470
* [x] The changes pass minimal style checks (see: https://twistedmatrix.com/trac/wiki/TwistedDevelopment#GettingYourPatchAccepted )
* [x] I have created a newsfragment in src/twisted/newsfragments/ (see: https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles )
* [ ] I have updated the automated tests.
* [ ] I have submitted the associated Trac ticket for review by adding the word `review` to the keywords field in Trac, and putting a link to this PR in the comment; it shows up in https://twisted.reviews/ now.

2020-03-08 05:12 UTC, glyph requested changes
Hi Martin!

Thanks so much for your contribution to Twisted.

The correct fix, here, if you want proper TLS security on `twisted.mail` connections, would be to drop `ClientContextFactory` entirely, and use `optionsForClientTLS`.  Dropping TLS 1.0 as a protocol version is good, but security-wise this change is almost meaningless, as `ssl.ClientContextFactory` doesn't verify certificates, or hostnames, or really provide ''any'' proper security properties.  (Separate to this change, it should be deprecated and removed from Twisted entirely.)

Dropping in `optionsForClientTLS` here should not be much harder that just fixing the protocol version, and it would have the added benefit that it would use a whole slew of ''other'' better security attributes as well.  Would you mind modifying your patch to do that?

Thanks!

2020-03-10 02:17 UTC, mmilata commented
@glyph thanks for quick review. I tried to replace the `ClientContextFactory` ctor call with `optionsForClientTLS`, however it requires the server hostname which I'm not quite sure how to pass to it without breaking the public interface. PTAL

Anyway the TLS negotiation goes further now before rejecting my server's self-signed cert:laughing:. Oh well, probably a good time to replace it with LetsEncrypt.

2020-03-12 00:10 UTC, mmilata commented
Installed LE certificate & now matrix-synapse can send emails through postfix configured to only use TLS1.1 or higher with this patch.

2020-03-17 06:51 UTC, glyph commented on src/twisted/mail/smtp.py
> +        self._hostname = None
This block here can be abbreviated to `self._hostname = kw.pop('hostname', None)`, saving a few lines of code :)

2020-03-17 06:51 UTC, glyph commented on src/twisted/mail/smtp.py
> +            from twisted.internet._sslverify import optionsForClientTLS
This is a public name, exposed as  [`twisted.internet.ssl.optionsForClientTLS`](https://twistedmatrix.com/documents/19.10.0/api/twisted.internet.ssl.html#optionsForClientTLS), so please import it from there.  (Maybe Twisted should use [publication](https://pypi.org/project/publication/) to avoid this problem...)

2020-03-17 06:51 UTC, glyph commented on src/twisted/mail/smtp.py
> +        tlsHostname = tlsHostname.decode("ascii")
This should be IDNA, not `"ascii"`.  See the internal `twisted.internet._idna` module for the shared utility for doing this.

2020-03-17 06:51 UTC, glyph commented on src/twisted/mail/smtp.py
>              except AttributeError:
I think this `except AttributeError` is now unnecessary.  Can you remove the whole `try` block around this code and see if any tests fail?

2020-03-17 06:53 UTC, glyph commented
Thanks again for your contribution!  I think the compatibility break is acceptable given the security needs here.  Please do re-add the `review` keyword so we notice it on twistedmatrix.com when you've addressed feedback, so we find it again.

2020-03-28 00:33 UTC, rodrigc approved these changes
I think @mmilata has addressed the review feedback, and this PR now looks OK.

2020-03-28 01:17 UTC, merged

2020-03-28 01:29 UTC, mmilata commented
Thanks @glyph & @rodrigc!

2020-03-28 02:11 UTC, rodrigc commented
@mmilata thank you for contributing to Twisted!

2020-04-25 22:21 UTC, Neustradamus commented
@rodrigc: Can you release a new version with this fix?

Several projects like Matrix waits you...
cc @clokep, @Half-Shot

@mmilata: Thanks!

Ticket: https://github.com/matrix-org/synapse/issues/6211

2020-05-05 11:04 UTC, rodrigc commented
@Neustradamus I am not the release manager for Twisted, so cannot release a new version.  @hawkowl is the release manager for Twisted.

2020-05-05 11:42 UTC, Neustradamus commented
@rodrigc: Thanks for your reply! :)

It is really important because a lot of people/servers have this problem...

@hawkowl: Thanks a lot in advance for a new release with this important fix.

2020-08-11 09:18 UTC, Neustradamus commented
People ask news about this security fix:
- https://twitter.com/CaptainKurtis/status/1292278623110660096

2020-10-14 00:29 UTC, Neustradamus commented
Dear @gjabell, @madpsy, @fadenb, @neilisfragile, @thereapman, @sbiberhofer, @henry-nicolas, @plamenh, @richvdh, @vmario89, @Chatcloud, @MisterAlainDev, @schwukas, @kaiyou, @babolivier, @mmilata, @clokep, @n3m3s1s, @Half-Shot, @exarkun, @anoadragon453: A good news, there are some "20.11.0" test-builds here:
- https://github.com/twisted/twisted/releases done by @rodrigc.

Time to test :)

cc: @glyph.

2020-10-14 10:18 UTC, richvdh commented
@Neustradamus you've already been asked not to mention the entire world over at https://github.com/matrix-org/synapse/issues/6211. If people are interested they will follow the issue themselves. Don't be obnoxious.

2021-02-16 00:20 UTC, Neustradamus commented
Good news the 21.02.0 RC1 is out!
- https://github.com/twisted/twisted/releases done by @rodrigc.

2021-03-02 03:54 UTC, Neustradamus commented
Good news, the 21.02.0 stable version is out!
- https://mail.python.org/archives/list/python-announce-list@python.org/thread/HHAY6XA5YRAYBA7IUL5UELX74H7W2X3V/
- https://github.com/twisted/twisted/releases/tag/twisted-21.2.0

Thanks a lot to @mmilata for this very important contribution and @rodrigc, @glyph and @twisted (Twisted Matrix Labs) team.