#12308 - Remove deprecated encryption CAST5 and Blowfish from ssh
twisted/twisted pull request #12310
Opened 2024-09-08 17:56 UTC by TFarrell89

## Scope and purpose

Fixes #12308 

Removes runtime warning. Change is deletion of lines, in list. 
Only tradeoff is inablity to simulate / test deprecated ciphers..

## Contributor Checklist:
I goofed on a prior PR without the newsfragment setup properly. should be in same PR now...

2024-09-08 18:07 UTC, adiroiban commented
Note that we also have this PR https://github.com/twisted/twisted/pull/11794

just a note. It this is merged, the other PR should be closed

2024-09-08 18:22 UTC, TFarrell89 commented
please review

2024-09-09 09:53 UTC, adiroiban approved these changes
Thanks for the fix.

I have updated the PR description to mention all the duplicate issues and PRs

There is a type in the newsfragment release notes for this PR

I made a suggestion for the release notes text.

It contains the exact cihper names... but it should be easier to search for the in the future

Also contains a reference to the Python class that was changed.

2024-09-09 09:53 UTC, adiroiban commented on src/twisted/conch/newsfragments/12308.bugfix
> +Blowfish and CAST5 encryoption were deprecated and are now removed from Twisted to remove runtime warning CryptographyDeprecationWarning
```suggestion
twisted.conch.ssh.SSHCiphers no longer supports the cast128-ctr, cast128-cbc, blowfish-ctr, and blowfish-cbc ciphers.
The Blowfish and CAST5 ciphers were removed as they were deprecated by the Python cryptography library.```

2024-09-09 09:57 UTC, adiroiban commented
Note that we also have this comment here https://github.com/twisted/twisted/issues/12138#issuecomment-2269891875

```
home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.8/site-packages/twisted/conch/ssh/transport.py:105: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  b"3des-cbc": (algorithms.TripleDES, 24, modes.CBC),
```

So in this PR we can look at removing the ciphers.

I a separate PR we can look at fixing the tripledes warning

---------

As a way to test it, the simples test is to make sure the warnings are not raised during test execution

2024-09-09 09:59 UTC, adiroiban approved these changes
I now see that these cipers are mentions in `docs/conch/man/conch.1` ... so we also need to update that file

https://github.com/twisted/twisted/blob/6f90df4b4059a758aff918ae95ab0f2adc2f200e/docs/conch/man/conch.1#L111

2024-09-09 09:59 UTC, adiroiban requested changes
I now see that these cipers are mentions in `docs/conch/man/conch.1` ... so we also need to update that file

https://github.com/twisted/twisted/blob/6f90df4b4059a758aff918ae95ab0f2adc2f200e/docs/conch/man/conch.1#L111

2024-09-09 12:34 UTC, TFarrell89 commented
Updated https://github.com/twisted/twisted/blob/6f90df4b4059a758aff918ae95ab0f2adc2f200e/docs/conch/man/conch.1#L111
to remove the deprecated ciphers from the list.

2024-09-09 12:42 UTC, adiroiban approved these changes
Many thanks for the changes and the cleanup here.

They looks good.

We have a few tests that mention blowfish and cast5 .... but I think that we can keep it.

The test input data is valid.
We can expect to receive algorightm names that we don't support.

https://github.com/twisted/twisted/blob/6f90df4b4059a758aff918ae95ab0f2adc2f200e/src/twisted/conch/test/test_transport.py#L1533-L1546

2024-09-09 12:44 UTC, TFarrell89 commented
Please let me know if other changes will help. Otherwise, I will back out
and leave it to you all.



On Mon, Sep 9, 2024 at 7:42 AM Adi Roiban ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> Many thanks for the changes and the cleanup here.
>
> They looks good.
>
> We have a few tests that mention blowfish and cast5 .... but I think that
> we can keep it.
>
> The test input data is valid.
> We can expect to receive algorightm names that we don't support.
>
>
> https://github.com/twisted/twisted/blob/6f90df4b4059a758aff918ae95ab0f2adc2f200e/src/twisted/conch/test/test_transport.py#L1533-L1546
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/twisted/twisted/pull/12310#pullrequestreview-2289799406>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABHVVHG5PRKXSGGQZ2MKTGDZVWJUVAVCNFSM6AAAAABN3FZBR2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEOBZG44TSNBQGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-09-09 14:10 UTC, merged

2024-09-09 14:11 UTC, adiroiban commented
Thanks for the changes. I have merged them.

I left https://github.com/twisted/twisted/issues/12138 open as we need a new PR to move the 3DES code