Add build date and version to HTML narrative documentation.
twisted/twisted pull request #1509
Opened 2021-02-06 22:31 UTC by adiroiban

## Scope and purpose

This only looks for HTML rendering of the narrative docs.

For API docs there will be separate ticket. This should be fixed in pydoctor and get it in Twisted with an update of pydoctor.

The Trac theme already has the version visible
https://twistedmatrix.com/documents/current/

![image](https://user-images.githubusercontent.com/204609/107130892-e7b44b80-68c9-11eb-869c-82dcadf2f8dc.png)

And this was updated to add copyright and build date in the footer.

-------------

We are left with Read The Docs variant which now has the version and date in the footer.

This was implemented by hijacking the Copyright field... In this way we don't need to modify the RTD theme.

This can be tested with the RTD build for this PR.

-------------

As a drive-by I have updated the copyright year to be automatically updated with the current year.

## Contributor Checklist:

* [x] The associated ticket in Trac is here: https://twistedmatrix.com/trac/ticket/3945
* [x] I ran `tox -e lint` to format my patch to meet the [Twisted Coding Standard](https://twistedmatrix.com/documents/current/core/development/policy/coding-standard.html)
* [x] I have created a newsfragment in src/twisted/newsfragments/ (see: [News files](https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles))
* [NA] I have updated the automated tests.
* [x] I have submitted the associated Trac ticket for review by adding the word `review` to the keywords field in Trac, and putting a link to this PR in the comment; it shows up in https://twisted.reviews/ now.

2021-02-08 16:33 UTC, altendky requested changes
It will be nice to have that info available.  Thanks.

2021-02-08 16:33 UTC, altendky commented on docs/_themes/twistedtrac/layout.html
> +        Copyright</a> {{ copyright }}.<br />
What anchor is this supposed to be closing?  Alternatively, I don't actually know html so it's something else entirely...

```suggestion
        Copyright {{ copyright }}.<br />
```

2021-02-08 16:33 UTC, altendky commented on docs/conf.py
> +copyright = "{}, Twisted Matrix Labs. Ver {}. Build at {}".format(
```suggestion
copyright = "{}, Twisted Matrix Labs. Ver {}. Built on {}".format(
```

2021-02-08 17:11 UTC, altendky commented
Ugh, looks like [cryptography just released](https://pypi.org/project/cryptography/#history) and broke everything (well, several macOS and Windows bits).

```

  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/opt/sqlite/include -I/usr/local/opt/sqlite/include -I/Users/runner/work/1/s/.tox/alldeps-withcov-posix/include -I/Users/runner/hostedtoolcache/Python/3.9.1/x64/include/python3.9 -c build/temp.macosx-10.14-x86_64-3.9/_openssl.c -o build/temp.macosx-10.14-x86_64-3.9/build/temp.macosx-10.14-x86_64-3.9/_openssl.o -Wconversion -Wno-error=sign-conversion
  build/temp.macosx-10.14-x86_64-3.9/_openssl.c:575:10: fatal error: 'openssl/opensslv.h' file not found
  #include <openssl/opensslv.h>
           ^~~~~~~~~~~~~~~~~~~~
  1 error generated.
  
      =============================DEBUG ASSISTANCE=============================
      If you are seeing a compilation error please try the following steps to
      successfully install cryptography:
      1) Upgrade to the latest pip and try again. This will fix errors for most
         users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
      2) Read https://cryptography.io/en/latest/installation.html for specific
         instructions for your platform.
      3) Check our frequently asked questions for more information:
         https://cryptography.io/en/latest/faq.html
      4) Ensure you have a recent Rust toolchain installed:
         https://cryptography.io/en/latest/installation.html#rust
      5) If you are experiencing issues with Rust for *this release only* you may
         set the environment variable `CRYPTOGRAPHY_DONT_BUILD_RUST=1`.
      =============================DEBUG ASSISTANCE=============================
  
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for cryptography
Failed to build cryptography
ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
```

2021-02-09 10:25 UTC, graingert commented
> Ugh, looks like [cryptography just released](https://pypi.org/project/cryptography/#history) and broke everything (well, several macOS and Windows bits).
> 
> ```
> 
>   gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/opt/sqlite/include -I/usr/local/opt/sqlite/include -I/Users/runner/work/1/s/.tox/alldeps-withcov-posix/include -I/Users/runner/hostedtoolcache/Python/3.9.1/x64/include/python3.9 -c build/temp.macosx-10.14-x86_64-3.9/_openssl.c -o build/temp.macosx-10.14-x86_64-3.9/build/temp.macosx-10.14-x86_64-3.9/_openssl.o -Wconversion -Wno-error=sign-conversion
>   build/temp.macosx-10.14-x86_64-3.9/_openssl.c:575:10: fatal error: 'openssl/opensslv.h' file not found
>   #include <openssl/opensslv.h>
>            ^~~~~~~~~~~~~~~~~~~~
>   1 error generated.
>   
>       =============================DEBUG ASSISTANCE=============================
>       If you are seeing a compilation error please try the following steps to
>       successfully install cryptography:
>       1) Upgrade to the latest pip and try again. This will fix errors for most
>          users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
>       2) Read https://cryptography.io/en/latest/installation.html for specific
>          instructions for your platform.
>       3) Check our frequently asked questions for more information:
>          https://cryptography.io/en/latest/faq.html
>       4) Ensure you have a recent Rust toolchain installed:
>          https://cryptography.io/en/latest/installation.html#rust
>       5) If you are experiencing issues with Rust for *this release only* you may
>          set the environment variable `CRYPTOGRAPHY_DONT_BUILD_RUST=1`.
>       =============================DEBUG ASSISTANCE=============================
>   
>   error: command '/usr/bin/gcc' failed with exit code 1
>   ----------------------------------------
>   ERROR: Failed building wheel for cryptography
> Failed to build cryptography
> ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
> ```

seems like it was bad luck and we ran a build after the sdist was available and before the wheel was available?

2021-02-09 13:15 UTC, altendky approved these changes

2021-02-09 13:17 UTC, merged