[10156] Capture sys.stdout from disttrial worker sub-proces.
twisted/twisted pull request #1571
Opened 2021-03-27 22:55 UTC by adiroiban

## Scope and purpose

This updates the log capturing of the distributed sub-process to also capture the data written to `sys.stdout`.

This is useful for poor man's debugging from a sub-process.

This is also helpful for a future PR in which the fd=1 (sys.stdout) will be used for AMP protoocol communication to make it easier to run distring on windows.

## Contributor Checklist:

* [x] The associated ticket in Trac is here: https://twistedmatrix.com/trac/ticket/10156
* [NO] I ran `tox -e lint` to format my patch to meet the [Twisted Coding Standard](https://twistedmatrix.com/documents/current/core/development/policy/coding-standard.html)
* [x] I have created a newsfragment in src/twisted/newsfragments/ (see: [News files](https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles))
* [x] The title of the PR starts with the associated Trac ticket number (without the `#` character).
* [x] I have updated the automated tests and checked that all checks for the PR are green.
* [ ] I have submitted the associated Trac ticket for review by adding the word `review` to the keywords field in Trac, and putting a link to this PR in the comment; it shows up in https://twisted.reviews/ now.
* [x] The merge commit will use the below format
  The first line is automatically generated by GitHub based on PR ID and branch name.
  The other lines generated by GitHub should be replaced.

```
Merge pull request #123 from twisted/4356-branch-name-with-trac-id

Author: adiroiban
Reviewer: 
Fixes: ticket:10156

Capture sys.stdout from distrial worker sub-processes and store it in the centralized log file.
```

2021-03-27 22:57 UTC, adiroiban commented
I have no executed `tox -e lint` as it fails and I don't have the energy now to debug tox... I will let the CI do its job and help me with that.

I did manually run `pyflakes`

```
$ tox --version
3.21.4 imported from /usr/lib/python3/dist-packages/tox/__init__.py
✔  ~/chevah/twisted [10156-distrial-sys-stdout|⚑ 2] 

22:56 $ tox -e lint
.tox create: /home/adi/chevah/twisted/.tox/.tox
ERROR: invocation failed (exit code 1), logfile: /home/adi/chevah/twisted/.tox/.tox/log/.tox-0.log
============================================================ log start ============================================================
RuntimeError: failed to build image setuptools because:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 57, in _install
    installer.install(creator.interpreter.version_info)
  File "/usr/lib/python3/dist-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 42, in install
    self._sync(filename, into)
  File "/usr/lib/python3/dist-packages/virtualenv/seed/embed/via_app_data/pip_install/copy.py", line 13, in _sync
    copy(src, dst)
  File "/usr/lib/python3/dist-packages/virtualenv/util/path/_sync.py", line 53, in copy
    method(norm(src), norm(dest))
  File "/usr/lib/python3/dist-packages/virtualenv/util/path/_sync.py", line 64, in copytree
    shutil.copy(src_f, dest_f)
  File "/usr/lib/python3.9/shutil.py", line 419, in copy
    copymode(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.9/shutil.py", line 308, in copymode
    chmod_func(dst, stat.S_IMODE(st.st_mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/adi/chevah/twisted/.tox/.tox/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/_typing.py'


============================================================= log end =============================================================
ERROR: InvocationError for command /usr/bin/python3 -m virtualenv --no-download --python /usr/bin/python3 .tox (exited with code 1)
/home/adi/chevah/twisted/.tox/.tox/bin/python: No module named tox
```

2021-03-27 22:58 UTC, adiroiban commented on src/twisted/trial/_dist/test/test_workertrial.py
> +        sys.stdout.flush()
I have no idea how to to test this in other way.

There is a unit test for `main()` but I also want to have a test in which the real code is exercised.

2021-03-28 02:01 UTC, adiroiban commented
This is ready for an initial review.

I don't know why mypy is not happy with

```
src/twisted/trial/_dist/workertrial.py:143:9: error: Statement is unreachable  [unreachable]
src/twisted/trial/_dist/test/test_workertrial.py:32:1: error: Cannot determine consistent method resolution order (MRO) for "FakeAM
```

I have check the line and with `$ trial --coverage -j1 twisted.trial._dist.test.test_options` the line is reached.
Also, I have no idea why is not happy with `class FakeAMP(AMP):`

2021-07-22 06:40 UTC, glyph requested changes
I think that this is a bad strategy.

One of the things I've learned from working with Python process pools is that one big reason to have a process pool is to isolate a sometimes-misbehaving C extension, and one of the ways that misbehaving C extensions can misbehave is by emitting messages *directly* to sys.stderr or sys.stdout.

I think it's important that, when we can, on UNIX at least (and maybe on Windows if we can sort out the file descriptor / standard I/O shenanigans?  maybe use a named pipe or something, Windows XP is dead, right?) we should stick to defaulting to capturing sys.stdout by using a non-stdio FD for inter-process communication.  If Windows really can't do that, then let's leave this code around.

2021-07-22 06:44 UTC, graingert commented
> Windows XP is dead, right?

Yep cpython 3.4 and 2.7 were last releases to support it

2021-07-22 10:36 UTC, adiroiban commented
Thanks for the review. I don't plan to work on this in the near future.

I have limited time so my plan was to get distributed trial on windows using the option that will require less effort.

2021-07-22 10:36 UTC, closed without merging