9792: Run inlineCallbacks callbacks outside of the _DefGen_Return exception context
twisted/twisted pull request #1606
Opened 2021-05-28 17:24 UTC by mstojcevich

## Scope and purpose

Python 3's implicit exception chaining will chain `_DefGen_Return` or `StopIteration` onto exceptions raised during `inlineCallbacks`-decorated function's callbacks because those exceptions are in the current exception context while the callbacks are running.

This PR changes `inlineCallbacks` to run the callbacks outside of the `_DefGen_Return`/`StopIteration` exception contexts.

## Contributor Checklist:

* [X] The associated ticket in Trac is here: https://twistedmatrix.com/trac/ticket/9792
* [X] I ran `tox -e lint` to format my patch to meet the [Twisted Coding Standard](https://twistedmatrix.com/documents/current/core/development/policy/coding-standard.html)
* [X] I have created a newsfragment in src/twisted/newsfragments/ (see: [News files](https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles))
* [X] The title of the PR starts with the associated Trac ticket number (without the `#` character).
* [ ] I have updated the automated tests and checked that all checks for the PR are green.
* [ ] I have submitted the associated Trac ticket for review by adding the word `review` to the keywords field in Trac, and putting a link to this PR in the comment; it shows up in https://twisted.reviews/ now.
* [ ] The merge commit will use the below format
  The first line is automatically generated by GitHub based on PR ID and branch name.
  The other lines generated by GitHub should be replaced.

```
Merge pull request #123 from twisted/4356-branch-name-with-trac-id

Author: <github_username>, <github_usernames_if_more_authors>
Reviewer: <github_username>, <github_username_if_more_reviewers>
Fixes: ticket:<trac_ticket_number>, ticket:<another_if_more_in_one_PR>

Long description providing a summary of these changes.
(as long as you wish)
```

2021-07-06 23:30 UTC, graingert commented on src/twisted/internet/defer.py
> +            callback_val = getattr(e, "value", None)
I think this is always present from 3.3+

```suggestion
            callback_val = e.value
```

2021-07-06 23:34 UTC, graingert commented on src/twisted/internet/defer.py
> +            callback_val = getattr(e, "value", None)
Asyncio also sets the result in the except block https://github.com/python/cpython/blob/3.9/Lib/asyncio/tasks.py#L265

2021-07-06 23:36 UTC, graingert commented on src/twisted/test/test_defer.py
> +            self.assertEqual(sys.exc_info(), (None, None, None))
Ah amazing I've always seen weird StopIteration related Tracebacks and had no idea why

2021-07-06 23:37 UTC, graingert requested changes
Can you test this with async/await also please

2021-07-11 10:14 UTC, graingert commented on src/twisted/internet/defer.py
> +            should_callback = True
I think this is cleaner with `break`


```python
while 1:
    ...
    callbackVal = e.value
    break
    ...
    callbackVal = e.value
    break

status.deferred.callback(callbackVal)
```

2021-07-22 08:16 UTC, graingert commented on src/twisted/internet/defer.py
> +            should_callback = True
here's the change https://github.com/twisted/twisted/commit/39ee52c3db975308a0d0ba336d4adb2673d48c5d

2021-08-04 07:50 UTC, graingert commented
@mstojcevich these tests pass already without the changes to `defer.py`: https://github.com/twisted/twisted/pull/1654

2021-08-17 23:46 UTC, mstojcevich commented
> @mstojcevich these tests pass already without the changes to `defer.py`: #1654

Oh, interesting. I originally wrote these having them sleep instead of yielding something that does nothing. I think having a real callback that came back from the reactor might have been important to have them fail without the changes. I'll see if I can get them working right.

2022-01-24 14:38 UTC, exarkun commented
Just noting there is a lot of overlap between this PR and https://github.com/twisted/twisted/pull/1662

2022-06-06 23:52 UTC, glyph commented
@mstojcevich I'm sorry we don't have a ton of review bandwidth these days, but would you mind resolving conflicts and addressing the feedback here?

2022-06-18 06:14 UTC, twm commented
I have merged forward and added tests based on the reproducer attached to [Trac #9792](https://twistedmatrix.com/trac/ticket/9792).

2022-06-19 08:36 UTC, adiroiban commented
@twm there is also #1662 , maybe we can have that merged first as it looks to me like it overlaps a bit

2022-06-19 09:20 UTC, graingert commented
@twm can you demo that the tests fail without the fix by reverting the fix on a new branch?

2022-06-20 09:15 UTC, adiroiban commented
I think that the demo part should be done by the reviewer.

As part of the review for #1662 I did just that, kept the tests, reverted the implementation changes, the test failed

2022-06-27 13:55 UTC, adiroiban requested changes
I am not sure if we still need this.

#1662 was merged and this PR now has conflicts.

Do we still need this PR?

thanks!

2022-07-03 06:14 UTC, twm commented
@adiroiban The fix in #1662 was equivalent, so we don't need the changes here. There are additional tests here, but as they didn't actually reproduce the bug I'm not sure of their value. At the least conflicts would need to be resolved, and the 0.1 second sleep in the tests reduced to 0.0. I don't plan to do any of that myself &mdash; my goal was to get whichever PR across the finish line.

2022-07-03 06:14 UTC, twm commented
Given the above I will close this for now, but if you are interested in landing these tests please feel free to reopen @mstojcevich!

2022-07-03 06:14 UTC, closed without merging