10210 Fix support for `contextvar.reset`
twisted/twisted pull request #1690
Opened 2022-01-31 19:25 UTC by richvdh

## Scope and purpose

We need to use the same copy of the context for each iteration of the generator function, to ensure that `.reset` works as expected.

## Contributor Checklist:

* [x] The associated ticket in Trac is here: https://twistedmatrix.com/trac/ticket/10210
* [x] I ran `tox -e lint` to format my patch to meet the [Twisted Coding Standard](https://twistedmatrix.com/documents/current/core/development/policy/coding-standard.html)
* [ ] I have created a newsfragment in src/twisted/newsfragments/ (see: [News files](https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles))
* [x] The title of the PR starts with the associated Trac ticket number (without the `#` character).
* [ ] I have updated the automated tests and checked that all checks for the PR are green.
* [ ] I have submitted the associated Trac ticket for review by adding the word `review` to the keywords field in Trac, and putting a link to this PR in the comment; it shows up in https://twisted.reviews/ now.
* [ ] The merge commit will use the below format
  The first line is automatically generated by GitHub based on PR ID and branch name.
  The other lines generated by GitHub should be replaced.

```
Merge pull request #123 from twisted/4356-branch-name-with-trac-id

Author: richvdh
Reviewer: <github_username>, <github_username_if_more_reviewers>
Fixes: ticket:10210

We need to use the same copy of the context for each iteration of the generator function,
to ensure that `.reset` works as expected.
```

2022-05-04 13:55 UTC, itamarst commented
I encountered the same problem (it impacts Eliot logging—https://eliot.readthedocs.io/en/stable/—which relies on contextvars). My reproducer:

```python
from twisted.internet.defer import inlineCallbacks
from twisted.internet.task import deferLater
from twisted.internet import reactor
from contextvars import ContextVar
from contextlib import contextmanager

MY_VAR = ContextVar("example")

@contextmanager
def set_var(name):
    print("setting!", name)
    token = MY_VAR.set(1)
    try:
        yield
    except Exception as e:
        print("resetting, exception!", name, e)
        MY_VAR.reset(token)
        raise
    else:
        print("resetting, success!", name)
        MY_VAR.reset(token)
        print("finished reseting", name)

@inlineCallbacks
def parent():
    with set_var("parent"):
        print("parent yielding")
        x = yield child()
        print("parent done yielding")
        return x

@inlineCallbacks
def child():
    with set_var("child"):
        print("child yielding")
        x = yield deferLater(reactor, 0.01, lambda: 123)
        print("child done yielding")
        return x

parent().addBoth(lambda r: print("Result", r) or reactor.stop())
reactor.run()
```

This PR fixes the problem, and conceptually makes sense to me as well.

2022-05-05 12:59 UTC, exarkun requested changes
Thanks!  The implementation change looks correct to me.  I left a comment about test factoring inline.  Once that is addressed I would be happy to see this merged.

2022-05-05 12:59 UTC, exarkun commented on src/twisted/test/test_defer.py
> +            # first try setting the var
This test is already excessively complex.  Can you please move testing for this fix into a new test method dedicated to this one specific behavior?

2022-05-10 16:32 UTC, richvdh commented on src/twisted/test/test_defer.py
> +            # first try setting the var
@exarkun thanks for the review! I've split this test up as you suggest in 83c9a66.

Please could you take another look?

2022-05-10 16:44 UTC, exarkun approved these changes
Thanks!

2022-05-10 16:45 UTC, merged