Added Support for HTTP multiple same content-length headers
twisted/twisted pull request #725
Opened 2017-02-28 22:03 UTC by anio

Added Support for HTTP multiple same content-length headers.

[RFC7230#section-3.3.2](https://tools.ietf.org/html/rfc7230#section-3.3.2):
>    If a message is received that has multiple Content-Length header
>    fields with field-values consisting of the same decimal value, or a
>    single Content-Length header field with a field value containing a
>    list of identical decimal values (e.g., "Content-Length: 42, 42"),
>    indicating that duplicate Content-Length header fields have been
>    generated or combined by an upstream message processor, then the
>    recipient MUST either reject the message as invalid or replace the
>    duplicated field-values with a single valid Content-Length field
>    containing that decimal value prior to determining the message body
>    length or forwarding the message.

2017-03-01 05:48 UTC, glyph commented
Hi @anio ! Thanks very much for your contribution. In the future, please file a ticket on Trac, as described in [the contributing guide](https://github.com/twisted/twisted/blob/b7f704386d4b2f383a947f7afb7a96c84eccb07c/CONTRIBUTING#L22-L30), and link it to a PR on github.  (While this system will eventually be simplified, for right now it helps us keep track of incoming PRs, given that much of our development tooling predates Github).

2017-03-01 05:49 UTC, glyph commented
I've created a ticket for you and submitted it for review so hopefully a reviewer will come along and look at it.  Thanks!

2017-03-01 08:15 UTC, Lukasa requested changes
Thanks for this! The patch looks reasonable to me, but it's really important that we add a test for this functionality. Do you mind doing that?

2017-03-02 12:20 UTC, anio commented
OK @glyph, thank you very much!

> @Lukasa: it's really important that we add a test for this functionality. Do you mind doing that?

Sorry @Lukasa,  i don't think!

2017-04-16 05:48 UTC, hawkowl commented
Superseded by https://github.com/twisted/twisted/pull/735

2017-04-16 05:48 UTC, closed without merging