Prepare for OpenSSL 1.1.1: Enable TLS 1.3 ciphers
twisted/twisted pull request #774
Opened 2017-05-02 14:00 UTC by tiran

TLS 1.3 does not use any of the existing cipher suites from TLS 1.2 and
earlier. A new set of cipher suites was introduced that only specify
bulk encryption, AEAD and PRF algorithms.

I expect that OpenSSL 1.1.1 will enable TLS 1.3 by default. If both
server and client have TLS version 1.3 enabled but have not configured
necessary cipher suites, handshake is going to fail.

Signed-off-by: Christian Heimes <christian@python.org>

2017-05-02 14:04 UTC, Lukasa commented
@tiran Thanks for this! By default this needs a [topfile](https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles) and a Twisted issue. If you're not up for doing that, I can take this over from you, add those parts, and then bully another committer into reviewing. Otherwise, I'm happy to take the lead on review.

2017-05-02 14:04 UTC, Lukasa requested changes
Agh, meant the above to be a review.

2017-05-02 14:10 UTC, lae-quay commented
How will we know if this works or not?

2017-05-02 14:12 UTC, exarkun commented
How will we know if this works or not?

2017-05-02 14:12 UTC, tiran commented
Thanks @Lukasa 

I have created https://twistedmatrix.com/trac/ticket/9128 and added a topfile. Is feature ok? It's technically both a feature and a bugfix for a bug that does not exist yet.

2017-05-02 14:13 UTC, exarkun commented
> I have created https://twistedmatrix.com/trac/ticket/9128 and added a topfile. Is feature ok? It's technically both a feature and a bugfix for a bug that does not exist yet.

It's just a feature.

I've added the "review" keyword to the trac ticket.  Please do that in the future whenever you have a PR that you want someone to look at.  Thanks.

2017-05-02 14:17 UTC, Lukasa commented
To know whether this works or not right now all we can do is run Twisted against a custom PyOpenSSL that can work with TLSv1.3. I don't even know if that is actually possible yet, though I suppose I should try. Regardless, OpenSSL has currently committed to those names in the cipher suite list, so I think this is a safe bet.

2017-05-02 15:02 UTC, exarkun commented
> run Twisted

Can you be more specific?  Twisted is a big pile of library code.  What specific thing can be run?  Is there a way to set up an HTTPS server and query it with an HTTPS client?  Something simpler?

2017-05-02 15:03 UTC, exarkun commented
(If it's not clear, the perspective I'm approaching this from is that there's no automated test coverage for this change.)

2017-05-02 15:08 UTC, Lukasa commented
>  Is there a way to set up an HTTPS server and query it with an HTTPS client? Something simpler?

In principle, yes, sure: use `twist web` to serve the files with an endpoint string that enables HTTPS, and then point `openssl s_client` against it with the appropriate ciphers enabled and see whether it works.

To *automate* that is moderately difficult, but only moderately: using some of the current interactive TLSMemoryBIO tests would also be absolutely fine for that. The *problem* with it is that to effectively interactively test this would require, again, the custom PyOpenSSL linked against OpenSSL 1.1.1 (as yet unreleased, maybe not even zero effort to build as cryptography may not yet link against it).

2017-05-02 15:35 UTC, exarkun commented
> The problem with it is that to effectively interactively test this would require, again, the custom PyOpenSSL linked against OpenSSL 1.1.1 (as yet unreleased, maybe not even zero effort to build as cryptography may not yet link against it).

It sounds like some CI build environment should be set up like this.   Perhaps not *now* (though I don't know why *not* now).  If we want the configuration to work, though, it should really be tested in CI.

2017-05-02 15:38 UTC, rodrigc commented
@Lukasa in future, for consistency, point folks to: https://twistedmatrix.com/trac/wiki/TwistedDevelopment#SubmittingaPatch

which has all the details about creating a ticket, creating topfile, etc., in one place.

2017-05-03 12:08 UTC, Lukasa requested changes

2017-05-03 12:08 UTC, Lukasa commented on src/twisted/topfiles/9128.feature
> +twisted.internet._sslverify now enables TLS 1.3 cipher suites.
So, sorry about this, but generally we try not to reference the complete path of private modules. It'd be better to say something like:

`twisted.protocols.tls.TLSMemoryBIOProtocol and anything that uses it indirectly including the TLS client and server endpoints now enables TLS 1.3 cipher suites.`

2017-05-22 16:20 UTC, Lukasa commented
Closed in favour of #787.

2017-05-22 16:20 UTC, closed without merging