Prevent a "exceptions.ValueError: need more than 1 value to unpack" t…
twisted/twisted pull request #778
Opened 2017-05-12 09:17 UTC by itshane

…raceback when the syntax of the Set-Cookie header is wrong.

When the Set-Cookie header contains ['HttpOnly;Secure'] value, it cannot split the value appropriately and throws a ValueError traceback.
The change just omits the wrong part of the header, therefore, a response can be gracefully processed.

2017-05-12 09:20 UTC, Lukasa commented
Thanks for this, this looks like a really good approach to this issue. However, it needs some enhancements per our [review process](https://twistedmatrix.com/trac/wiki/ReviewProcess) before we can merge:

1. You need to open a ticket on twistedmatrix.com to track the work. This ticket should explain the issue.
2. You'll need to write a unit test to demonstrate the issue and to demonstrate that your patch fixes the issue.
3. You'll need a topfile explaining the patch.

If you need any help with any of this, just let me know.

2017-05-15 12:00 UTC, itshane commented
@Lukasa: I've amended the pull request with the requested changes, please take a look when possible.

2017-05-15 12:17 UTC, Lukasa requested changes
Ok, I've left a note about some docs stuff. When that gets sorted out I'll push to the builders. You'll want to re-submit your ticket for review.

2017-05-15 12:17 UTC, Lukasa commented on src/twisted/web/client.py
> +        @type headers: L{list}
`headers` cannot possibly be a `list`: it has to be string-indexable. The rest of the code suggests it's a `dict`.

2017-05-15 16:16 UTC, itshane commented
@Lukasa: Updated.

2017-08-13 06:21 UTC, rodrigc approved these changes
OK, @Lukasa's feedback was incorporated.

2017-08-13 07:43 UTC, merged