Raise CannotDetermineNamespaceError instead of KeyError when unable to determine namespace from calling context.
twisted/twisted pull request #792
Opened 2017-05-23 05:45 UTC by wsanchez

See https://twistedmatrix.com/trac/ticket/7930

2017-05-23 07:53 UTC, glyph requested changes
Thanks for following up on this fix.

I feel a little bit weird about `Logger` being documented and expected to raise an exception when called from a weird context.  I think this should be documented in more depth; at the very least a `@raises` in its class docstring or something.

Plus, the tests are failing.  Please fix and resubmit.

2017-05-23 07:53 UTC, glyph commented on src/twisted/logger/test/test_logger.py
> +        L{CannotDetermineNamespaceError} is raised when unable to determine the
One should write docstrings in the active voice.  (i.e.: is raised?  raised by whom?)

2017-05-23 07:53 UTC, glyph commented on src/twisted/newsfragments/7930.bugfix
> +Raise CannotDetermineNamespaceError instead of KeyError when unable to
As per the examples in https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles this should refer to a fully-qualified python name; what is it that raises the exception?

2017-06-26 23:06 UTC, wsanchez commented
Since Glyph is feeling squeamish about `Logger()` raising on purpose instead of on accident when called from a crazy context, I'll try setting the namespace to "<unknown>" instead.

2017-06-27 00:15 UTC, glyph commented
> Since Glyph is feeling squeamish about Logger() raising on purpose instead of on accident when called from a crazy context, I'll try setting the namespace to "<unknown>" instead.

Thanks, appreciated :).

I should note for posterity that this squeamishness is very nearly exclusive to `Logger`; in almost every case, blowing up is the right thing to do, it's just that `Logger` is the one thing that you use to figure out how you blew up when that happens :)

2017-06-27 01:14 UTC, wsanchez commented
@glyph: Cool.  Putting back up for review.

2017-07-04 03:25 UTC, glyph approved these changes

2017-07-04 03:25 UTC, glyph commented
👍 Looking good. Will merge.

2017-07-04 03:27 UTC, merged