Fix traceback forwarding with inlineCallbacks on python 3
twisted/twisted pull request #813
Opened 2017-06-12 16:06 UTC by tardyp

fix for https://twistedmatrix.com/trac/ticket/9175#9175

2017-06-14 04:39 UTC, rodrigc requested changes
@tardyp instead of using _PY3, would it be possible to use `twisted.python.compat._bytesChr` here?

2017-06-14 07:01 UTC, tardyp commented
@rodrigc bytesChr will not work here as on python3 we need to have an int, and on py2 we need a single byte native string. bytesChr always return bytes https://github.com/twisted/twisted/blob/twisted-17.5.0/src/twisted/python/compat.py#L759

2017-06-14 07:11 UTC, rodrigc commented
OK.
There is a test failure with this patch: https://travis-ci.org/twisted/twisted/jobs/242081518

```
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/home/travis/build/twisted/twisted/build/py33-alldeps-withcov-posix/lib/python3.3/site-packages/twisted/test/test_failure.py", line 914, in test_throwExceptionIntoGenerator
    self.assertEqual(traceback.extract_tb(stuff[0][2])[-1][-1], "1/0")
  File "/home/travis/build/twisted/twisted/build/py33-alldeps-withcov-posix/lib/python3.3/site-packages/twisted/trial/_synctest.py", line 432, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/opt/python/3.3.5/lib/python3.3/unittest/case.py", line 641, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/opt/python/3.3.5/lib/python3.3/unittest/case.py", line 1020, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
twisted.trial.unittest.FailTest: 'yield' != '1/0'
- yield
+ 1/0
twisted.test.test_failure.ExtendedGeneratorTests.test_throwExceptionIntoGenerator
-------------------------------------------------------------------------------
```

2017-08-14 13:31 UTC, tardyp commented
added test fixes from @jafd thanks to him. Sorry for forgetting about this PR :-/

2017-08-14 15:07 UTC, rodrigc requested changes

2017-08-14 15:07 UTC, rodrigc commented on src/twisted/test/test_failure.py
>          self.assertEqual(len(newFailures), 1)
Please remove import of _PY3 from this file.  It is now an unused import

2017-08-14 15:07 UTC, rodrigc commented on src/twisted/python/failure.py
> +from twisted.python.compat import _PY3
Combine this import with previous line

2017-08-14 15:07 UTC, rodrigc commented on src/twisted/newsfragments/9175.bugfix
> +Fix traceback forwarding with inlineCallbacks on python 3.
Please add a newsfragment for 5949.  It looks like you fixed that as well.

2017-08-14 20:53 UTC, rodrigc commented
@itamarst @exarkun @moshez @glyph Please review this

2017-08-17 09:50 UTC, rodrigc approved these changes

2017-08-17 09:50 UTC, rodrigc commented on src/twisted/python/failure.py
> +        _yieldOpcode = chr(opcode.opmap["YIELD_VALUE"])
I've tested this on Python 2 and Python 3.  This is the right fix, because further down,
we dereference a single element in a bytes array

2017-08-17 09:50 UTC, rodrigc commented on src/twisted/python/failure.py
>              lastFrame.f_code.co_code[lastTb.tb_lasti] != cls._yieldOpcode):
`lastFrame.f_code.co_code is an array of `bytes`.  On Python 2, `lastFrame.f_code.co_code[lastTb.tb_lasti]` returns a character, such as 'c'.  On Python 3, lastFrame.f_code.co_code[lastTb.tb_lasti]` returns an int, such as 99.

2017-08-17 17:24 UTC, merged