Added --add-header to twist web
twisted/twisted pull request #850
Opened 2017-07-31 00:58 UTC by alex

Fixes #9241

2017-07-31 07:05 UTC, Lukasa requested changes
Thanks for this @alex! Can you add a news file for me please? I also think we should probably have tests for this functionality.

2017-07-31 11:07 UTC, alex commented
@Lukasa There is a newsfile. Do you have a suggestion as to where to look for the appropriate tests to imitate :-)

2017-07-31 14:13 UTC, derwolfe requested changes
@alex thanks for putting this PR up! This definitely would have saved me from writing some code a while back. 

The main blocker that I can see is testing. I'd suggest adding some tests that 
1. exercise the new functionality of the options class. This would make it so you could confidently show that using `--add-header` does what you expect.
2. figure out a way to exercise the new service code. I'm not exactly sure what the best way forward would be here. I think it would be useful to know that given an HTTP request, you are able to get an HTTP response out that has the headers you expect. But, I could see there being an argument that this might be too high level of a test to live in `test_tap`. If that is the case, or the test is too complex, maybe it would be sufficient to show that the resource being used as part of `makeService` is an instance of `_AuthHeadersResource`?

Also, please feel free to ask for another review. While I do think I understand how twisted's options logic is tested and how to test `makeService`, I'm not super confident that my suggestions for testing are complete :)

2017-07-31 14:13 UTC, derwolfe commented on src/twisted/web/tap.py
> +        headers = [h.split(b':', 1) for h in config['extraHeaders']]
It feels like the logic for parsing the `--add-headers` option should live outside of `makeService`. The main reason for this would be ease of testability. I do think I see why this can't live on the options class: you are using `opt_add_header` which will take each instance of `--add-header "H1:HV1" --add-header "H2:HV2"` and join them together in a list.

Some examples of how to test option parsing logic can be found in [twisted/web/test/test_tap.py](https://github.com/twisted/twisted/blob/trunk/src/twisted/web/test/test_tap.py). For other examples, you could look at how conch's options or mail's options are tested (not that I'm sure they are canonical, but they do seem to conform to the tests that I've written for my own tap files).

2017-07-31 14:13 UTC, derwolfe commented on src/twisted/web/tap.py
> +    def opt_add_header(self, header):
This could use a docstring. :)

2017-07-31 21:43 UTC, alex commented
@Lukasa, @derwolfe: Added tests!

2017-08-01 06:39 UTC, Lukasa commented
So while I'm running all the builders, I have a note here: this doesn't work if you specify the same header more than once. That if, is you do `--add-header "K1: V1" --add-header "K1: V2"` you will get only `K1: V2` in the output.

I *think* for now this limitation is fine: it's easily worked around by users, if they're interested in doing so. It would be good if we could document it somewhere, just so people know that it's a deliberate omission and not an oversight.

2017-08-01 11:42 UTC, alex commented
@Lukasa Repeated headers are handled now.

2017-08-01 12:00 UTC, Lukasa approved these changes
Cool, I'm going to get the buildbot to test this and then we should be good to go.

2017-08-01 13:43 UTC, merged