Fix nested list indentation
twisted/twisted pull request #868
Opened 2017-08-17 07:46 UTC by twm

While looking at the docs I noticed that a few lists were rendered with structures like:

```html
<ol><li>...</li></ol>
<blockquote>
  <ul>
    <li>...</li>
  </ul>
</blockquote>
<ol start="2"><li>...</li></ol>
```

This is noticeable visually because the nested list has excessive left indentation. This happens because of a conflict between the reST syntax for nested lists and blockquotes. Specifically, if you under-indent a nested list, docutils takes it as a top-level blockquote containing a list. For example, this syntax is off:

```rst
- foo
 - bar (not enough indentation)
```
 While this is correct:

```
- foo
  - bar
```

There is also [the opposite problem](https://twistedmatrix.com/documents/current/installation/howto/optional.html): over-indented nested lists adding blockquotes.

The simple rule is that the content of a list must be indented exactly to match the first character of text.

I did a pass over all of the .rst documents in the `docs/` directory and fixed this in a few places, and also changed some enumerated lists to use the `#.` syntax instead of explicit numerals, as this makes it easier to see when the syntax is off (because the numbering restarts).

This addresses https://twistedmatrix.com/trac/ticket/9256

2017-08-17 08:08 UTC, rodrigc commented
Please follow all the steps at: https://twistedmatrix.com/trac/wiki/TwistedDevelopment#SubmittingaPatch
* need a newsfragment
* need to set *review* keyword on Trac ticket

2017-08-18 03:36 UTC, twm commented
@rodrigc Yup, on the way (I was interrupted mid-push).

2017-08-19 08:19 UTC, markrwilliams requested changes
Documentation improvements are always fantastic!

The affected docs look good when rendered locally.

The news fragment should be a `.doc`, because even though they're small, they're very useful changes and worth recording.   Please update it.

I've pushed this branch to the builders, so you can see if there are any issues in the meantime.

2017-08-19 08:19 UTC, markrwilliams commented on docs/core/howto/ssl.rst
> +1. Identity: TLS servers (and sometimes clients) present a certificate, offering proof of who they are, so that you know who you are talking to.
Why not make this `#.` as well?

2017-08-26 15:43 UTC, twm commented on docs/core/howto/ssl.rst
> +1. Identity: TLS servers (and sometimes clients) present a certificate, offering proof of who they are, so that you know who you are talking to.
I could go either way, as the text preceding the list says "three things", so okay. Probably best to encourage this syntax everywhere.

2017-08-26 15:58 UTC, twm commented
Thank you for the review! I believe that I have addressed all of your feedback.

2017-08-30 09:32 UTC, markrwilliams approved these changes

2017-09-14 08:04 UTC, merged