9274 agent docstring
twisted/twisted pull request #885
Opened 2017-09-02 04:35 UTC by jlitzingerdev

Pull request for https://twistedmatrix.com/trac/ticket/9274.

2017-09-02 05:54 UTC, jlitzingerdev commented
Not sure about the 3.3 failure, but I did forget the news fragment so I'll add that and resubmit.

2017-09-13 22:11 UTC, rodrigc requested changes

2017-09-13 22:11 UTC, rodrigc commented on src/twisted/web/client.py
> +        @type reactor: L{IReactorTCP} and
Yes, you are absolutely right.  Thanks for catching this.
Your wording changes are mostly good, except for the `@type`.

In all the places where you specified `@type` can you change to:

```
@type reactor: type of reactor must be same as type used in L{HostnameEndpoint.__init__}
```

That will be correct, and prevent a skew in documentation between client.py and HostnameEndpoint

2017-09-15 04:31 UTC, rodrigc approved these changes
Looks good.

2017-09-15 06:24 UTC, merged