Remove twisted.python.win32.getProgramsMenuPath and twisted.python.win32.getProgramFilesPath
twisted/twisted pull request #921
Opened 2017-10-28 21:13 UTC by rodrigc

https://twistedmatrix.com/trac/ticket/9312

twisted.python.win32.getProgramsMenuPath and twisted.python.win32.getProgramFilesPath
were deprecated in Twisted 15.3.0:
https://github.com/twisted/twisted/blob/trunk/NEWS.rst#deprecations-and-removals-21

and can now be removed

2017-10-28 21:15 UTC, rodrigc commented
@opalmer please review

2017-10-28 22:40 UTC, opalmer approved these changes
Looks good. I grepped around in the source code and don't see these used anywhere. I seem to recall asking about these functions a while back on the mailing list and the feedback was basically they're not used anywhere to the best of anyone's knowledge (I'd have to go looking for the thread to dig it up...)

2017-10-29 00:49 UTC, opalmer approved these changes

2017-10-29 01:07 UTC, tdsmith commented on src/twisted/newsfragments/9312.removal
> +twisted.python.win32.getProgramsMenuPath and twisted.python.win32.getProgramFilesPath were deprectaed in Twisted 15.3.0 and have now been removed.
nit: s/deprectaed/deprecated/

2017-10-29 01:17 UTC, opalmer requested changes

2017-10-29 01:17 UTC, opalmer commented on src/twisted/newsfragments/9312.removal
> +twisted.python.win32.getProgramsMenuPath and twisted.python.win32.getProgramFilesPath were deprectaed in Twisted 15.3.0 and have now been removed.
+1 agreed, I missed this.

2017-10-29 01:47 UTC, opalmer approved these changes

2017-10-29 22:02 UTC, merged