Work around buggy Cygwin behavior w.r.t. broken pipes.
twisted/twisted pull request #925
Opened 2017-11-08 11:37 UTC by embray

Ensure that the parent end of the stdin pipe gets closed on Cygwin and
doesn't cause the reactor to hang.  See
https://twistedmatrix.com/trac/ticket/9323

2017-11-26 18:15 UTC, adiroiban requested changes
Thanks for working on this.

Please see my inline comments.

As a must, I think that we need:

* see if new members should be public
* see if we need the  function at all
* see how to test the changes

-----------

AFIK we don't have any slaves for cygwin so I don't know how are we going to do automated and continuous tests for this.

Have you used python + cygwin on appveyour 

It would be great to see a cygwin + python build for Twisted so that we can cover this platform on a regular basis.

Right now I don't have time to investigate how to run python on cygwin and then how to run in on appveyor but I am happy to do extra hours to review such work.

-------

You can also try to get someone over IRC or mailing list to manually run a one time test this of this on Cygwin and review that changes are working.

but it would be best to have automated and continous tests for Cygwin.

2017-11-26 18:15 UTC, adiroiban commented on src/twisted/internet/process.py
> +brokenCygwinPipeBehavior = detectCygwinBrokenPipeBehavior()
Do we really need to have these 2 new methods part of the public API of process?

I know that we have that for brokenLinuxPipeBehavior ... but I don't see why people using Twisted should care about this :)

2017-11-26 18:15 UTC, adiroiban commented on src/twisted/internet/process.py
> +                    list(self.pipes.keys()) == [0]):
I think that this needs a comment, or refactor this long condition into a dedicated boolean variable.

I know that the ticket description is comprehensive but when people will read this code, it will take extra effort to look at the commit id, and then detect in which commit it  was merged in trunk and from there get the ticket id, and then go to Trac to read the discussions.

2017-11-26 18:15 UTC, adiroiban commented on src/twisted/internet/process.py
> +                                        forceReadHack=not brokenCygwinPipeBehavior)
maybe this can be left as it is, and overwrite this forceReadHack only for Cygwin, inside the factory/protocol implementation

2017-11-26 18:15 UTC, adiroiban commented on src/twisted/internet/process.py
> +    return not reads
I don't quite understand why we get this from here.

From the Trac ticket, my understand is that Cygwin always has this behaviour as there versions of Cygwin in which the pipes are not "broken"?

The docstring on this method does not contain "On some Cygwin" versions

2017-11-26 18:15 UTC, adiroiban commented on src/twisted/internet/process.py
> +        elif not brokenCygwinPipeBehavior:
my suggestion is to put this into a separate `if brokenCygwinPipeBehavior` and overwrite forceReadHack together with a comment

2017-11-28 14:07 UTC, embray commented on src/twisted/internet/process.py
> +                                        forceReadHack=not brokenCygwinPipeBehavior)
Yeah, I debated going either way on that.  Tbh I think the `forceReadHack` argument should not be passed on here at all, and instead allow the implementation to check whether or not it's needed for the relevant platform.

2024-05-03 19:44 UTC, glyph commented
See ticket closure explanation.

2024-05-03 19:44 UTC, closed without merging