Do not crash if we try to run wsgi over a Unix socket
twisted/twisted pull request #980
Opened 2018-03-25 04:21 UTC by rodrigc

https://twistedmatrix.com/trac/ticket/5406

2018-03-25 04:41 UTC, rodrigc commented
@ewdurbin you mentioned here: https://twitter.com/EWDurbin/status/976616064170758145

that you would like to run `twistd` over wsgi for https://pypi.org

If you have time, can you quickly try out this patch by installing in a virtualenv directly from this branch by doing:

```
python -m pip install git+https://github.com/twisted/twisted.git@5406-rodrigc-wsgi-unix-socket
```

and provide feedback?

Thanks.

2018-03-25 04:44 UTC, rodrigc commented
@EWDurbin if you install this branch, you will also get a fix for https://twistedmatrix.com/trac/ticket/7704 done by @markrwilliams in https://github.com/twisted/twisted/pull/975

2018-03-25 10:13 UTC, rodrigc commented
In ticket:5406, @exarkun referred to this thread https://mail.python.org/pipermail/web-sig/2012-January/005097.html .  The WSGI standard doesn't take into account Unix sockets, so other servers like gunicorn and CherryPy deviate from the standard to work with Unix sockets.

2018-03-26 23:23 UTC, ewdurbin commented
@rodrigc thank you! i'll get a canary of this out as soon as I determine how to get pip-compile to allow it :-p

2018-03-27 08:12 UTC, markrwilliams commented
This will [break Django](https://github.com/django/django/blob/master/django/http/request.py#L82).  We need a [different approach](https://twistedmatrix.com/trac/ticket/5406#comment:10).

2018-04-08 01:18 UTC, rodrigc commented
@markrwilliams actually, I tried my patch and it did not break Django.

I created a very simple django project called mysite, then started it with:

```
twist web --port=unix:/tmp/sock --wsgi mysite.wsgi.application
```

Then I tried to access it via:

```
curl --unix-socket /tmp/sock http://example.invalid/
```

At first, Django returned an error message:

```
Invalid HTTP_HOST header: 'example.invalid'. You may need to add 'examle.invalid' to ALLOWED_HOSTS.
```

But then in my Django project, I added to mysite/settings.py:

```
ALLOWED_HOSTS = ['example.invalid']
```

I then re-ran the curl command, and Django successfully returned the web page.

Is there some other scenario you are referring to where you would expect Django to fail?

2018-04-08 01:57 UTC, markrwilliams commented
Per the links I shared, and as explained in the Trac ticket I linked to, there are two cases that fail:

1. [HttpRequest.get_port](https://docs.djangoproject.com/en/2.0/ref/request-response/#django.http.HttpRequest.get_port) for all HTTP requests;
2. [HttpRequest.get_host](https://docs.djangoproject.com/en/2.0/ref/request-response/#django.http.HttpRequest.get_host) for HTTP 1.0 requests without a `Host` header.

Here's a reproducer:

https://github.com/markrwilliams/django-demo

2018-04-08 01:59 UTC, markrwilliams commented
Here's an incomplete branch that works:

https://github.com/twisted/twisted/compare/5406-wsgi-unix-socket

It needs https://twistedmatrix.com/trac/ticket/9400 and https://twistedmatrix.com/trac/ticket/9403 before it can be completed.

Here's a branch that addresses both of those:

https://github.com/twisted/twisted/compare/9400-getRequestHostname-exception

2018-04-08 16:26 UTC, rodrigc commented
@markrwilliams thanks for the Django test case.  I modified my patch, and ran it against
your Django testcase and it works.

2018-05-28 22:17 UTC, glyph requested changes
Much as I'd like to land this soon, this branch introduces new behavior but doesn't introduce tests to cover it, so we do need to block on that.

I really like the implementation strategy over on https://github.com/twisted/twisted/compare/5406-wsgi-unix-socket since it includes both unit tests and a referentially transparent `_extractAddresses` with an expansive docstring (although it would be nice if it included even more of the information from https://twistedmatrix.com/trac/ticket/5406#comment:10 since that context is useful).  If it could be fixed up to pass tests, that would be great.

2022-01-19 00:40 UTC, closed without merging